/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // TripMate AI 디자인 시스템 색상 토큰
        "primary": "#00658d",
        "primary-light": "#00aeef",
        "on-primary": "#ffffff",
        "primary-container": "#c6e7ff",
        "on-primary-container": "#003e58",
        "primary-fixed": "#c6e7ff",
        "primary-fixed-dim": "#82cfff",
        "on-primary-fixed": "#001e2d",
        "on-primary-fixed-variant": "#004c6b",
        "inverse-primary": "#82cfff",

        "secondary": "#535f70",
        "on-secondary": "#ffffff",
        "secondary-container": "#d7e3f7",
        "on-secondary-container": "#101c2b",
        "secondary-fixed": "#d7e3f7",
        "secondary-fixed-dim": "#bbc7db",

        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#00658d",

        "on-surface": "#191c1d",
        "on-surface-variant": "#3e4850",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",

        "background": "#f8f9fa",
        "on-background": "#191c1d",

        "outline": "#6e7881",
        "outline-variant": "#bdc8d1",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        "tertiary": "#785900",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ce9b00",
        "on-tertiary-container": "#4a3600",
        "tertiary-fixed": "#ffdf9e",
        "tertiary-fixed-dim": "#fabd00",
        "on-tertiary-fixed": "#261a00",
        "on-tertiary-fixed-variant": "#5b4300",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.375rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        gutter: "16px",
        sm: "8px",
        lg: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        xs: "4px",
        md: "16px",
        xl: "32px",
        "max-width-content": "1200px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Noto Sans KR", "Inter", "sans-serif"],
        "body-md": ["Inter", "Noto Sans KR", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Noto Sans KR", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "Noto Sans KR", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "Noto Sans KR", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "Noto Sans KR", "sans-serif"],
        "label-md": ["Inter", "Noto Sans KR", "sans-serif"],
        "label-sm": ["Inter", "Noto Sans KR", "sans-serif"],
        "body-lg": ["Inter", "Noto Sans KR", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "zoom-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        shimmer: "shimmer 2s infinite linear",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "slide-up": "slide-up 0.6s ease-out forwards",
        "zoom-in": "zoom-in 0.3s ease-out forwards",
      },
    },
  },
  plugins: [],
}
